server:
  port: 8080

spring:
  sql:
    init:
      mode: always
  application:
    name: reservation-pos-server
  r2dbc:
    url: r2dbc:mysql://210.121.177.150:3306/ReservationPos
    username: gijunpark
    password: park9832
    properties:
      ssl: false
      sslMode: DISABLED
      connectionTimeZone: Asia/Seoul
      useServerPrepareStatement: true
  jackson:
    serialization:
      indent-output: true
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

logging:
  level:
    root: INFO
    com.gijun.reservationpos: DEBUG
    io.r2dbc: DEBUG
    org.springframework.r2dbc: DEBUG
