server:
  port: ${SERVER_PORT:52001}

spring:
  sql:
    init:
      mode: always
  r2dbc:
    url: ${DB_URL:r2dbc:mysql://210.121.177.150:3306/ReservationPos}
    username: ${DB_USERNAME:gijunpark}
    password: ${DB_PASSWORD:park9832}
    properties:
      ssl: false
      sslMode: DISABLED
      connectionTimeZone: Asia/Seoul
      useServerPrepareStatement: true

logging:
  level:
    root: WARN
    com.gijun.reservationpos: INFO
