server:
  port: 52001

spring:
  application:
    name: reservation-pos-server
  r2dbc:
    url: ${DB_URL:r2dbc:mysql://210.121.177.150:3306/ReservationPos}
    username: ${DB_USERNAME:gijunpark}
    password: ${DB_PASSWORD:park9832}
    properties:
      ssl: false
      sslMode: DISABLED
      connectionTimeZone: Asia/Seoul
      useServerPrepareStatement: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

logging:
  level:
    root: WARN
    com.gijun.reservationpos: INFO
